fileLocation: log.txt
defaultPublisherType: TOPIC # Publisher types are case sensitive
defaultTopicName: sample_topic
defaultRestEndpoint: http://devtools.com/message/
keywords:
  - 
    text: halt
    message: Sample text
    publisherType: TOPIC
    topicName: topic1

  - 
    text: exception
    publisherType: REST